# Generated by Django 4.1.2 on 2022-10-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='guest-user.jpg', upload_to='profile_pics'),
        ),
    ]
